services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_secret_tcp
      - MYSQL_DATABASE=todo-list
    volumes:
      - mysql:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - face
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7.4-alpine
    volumes:
      - redis:/data
    networks:
      - face
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5
  
  face-regconition-service:
    build: ./face-regconition-service
    networks:
      - face
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy

  face-reg-engine:
    build: ./face-reg-engine
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/FACE_ENGINE?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password_secret_tcp
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - MINIO_URL=http://minio
      - MINIO_PORT=9000
      - MINIO_USERNAME=admin
      - MINIO_PASSWORD=123456789$
      - MINIO_BUCKET=face-bucket
      - MINIO_AUTOCREATE=true
        #- FACE_HOST_NAME=http://host.docker.internal:5000
    networks:
      - face
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_started
    restart: on-failure

  auth-service:
    build: ./auth-service
    environment:
      - DB_DSN=root:root_password_secret_tcp@tcp(mysql:3306)/todo-auth?charset=utf8mb4&parseTime=True&loc=Local
      - GIN_PORT=3100
      - GRPC_PORT=3101
      - GRPC_USER_ADDRESS=user-service:3201
      - JWT_SECRET=very-important-please-change-it!
      - JWT_ACCESS_TOKEN_EXPIRY=15m
      - JWT_REFRESH_TOKEN_EXPIRY=7d
      - TOKEN_CLEANUP_INTERVAL=1h
      - REDIS_URL=redis:6379
    networks:
      - face
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  user-service:
    build: ./profile-service
    environment:
      - DB_DSN=root:root_password_secret_tcp@tcp(mysql:3306)/todo-user?charset=utf8mb4&parseTime=True&loc=Local
      - GIN_PORT=3200
      - GRPC_PORT=3201
      - GRPC_AUTH_ADDRESS=auth-service:3101
    networks:
      - face
    depends_on:
      mysql:
        condition: service_healthy
    
  ai-backend-service:
    build: ./ai-backend-service
    ports:
      - "3000:3000"
    environment:
      - DB_DSN=root:root_password_secret_tcp@tcp(mysql:3306)/todo-list?charset=utf8mb4&parseTime=True&loc=Local
      - GIN_PORT=3000
      - GRPC_AUTH_USER_ADDRESS=auth-service:3101
      - GRPC_PROFILE_ADDRESS=user-service:3201
      # - FACE_HOST=http://host.docker.internal:8080/face/v1/api/
    networks:
      - face
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy

  app-fe:
    build: ./gui-app
    ports:
      - "80:80"   # only expose frontend
    networks:
      - face
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VITE_APP_API_URL=http://localhost:3000
    depends_on:
      ai-backend-service:
        condition: service_started

  
  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 123456789$
    ports:
      - "9000:9000"   # API port for SDK/app
      - "9001:9001"   # Console port for web UI
    volumes:
      - ./data:/data
    networks:
      - face
    command: server /data --console-address ":9001"

networks:
  face:
    driver: bridge

volumes:
  mysql:
  redis:

