apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: face-microservice
  namespace: argocd
spec:
  description: Face Recognition Microservice Project
  sourceRepos:
    - 'https://github.com/mario-noobs/face-microservice.git'
    - 'git@github.com:mario-noobs/face-microservice.git'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: apps
      kind: '*'
    - group: batch
      kind: '*'
    - group: autoscaling
      kind: '*'
    - group: networking.k8s.io
      kind: '*'
