apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognition-service
  namespace: face-app
spec:
  template:
    spec:
      containers:
        - name: face-recognition-service
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          env:
            - name: OMP_NUM_THREADS
              value: "1"
            - name: MKL_NUM_THREADS
              value: "1"
