sonar.projectKey=face-microservice-backend
sonar.organization=face-microservice
sonar.host.url=https://sonarcloud.io
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=**/dto/**,**/entity/**,**/config/**,**/BackendApplication.java
sonar.coverage.exclusions=**/dto/**,**/entity/**,**/config/**,**/BackendApplication.java
