apiVersion: v1
kind: ConfigMap
metadata:
  name: face-service-config
  namespace: face-app
data:
  FLASK_ENV: "production"
  MODEL_S3_ENDPOINT: "http://minio.face-infra.svc.cluster.local:9000"
  MODEL_S3_BUCKET: "face-models"
  MODEL_CACHE_DIR: "/app/model_cache"
  ENABLED_MODELS: "retinaface_mobilenet,facenet_mobilenet"
  LOG_LEVEL: "INFO"
