apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: face-app
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "dev"
  DB_HOST: "mysql.face-infra.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "backend_db"
  DB_USERNAME: "root"
  REDIS_HOST: "redis.face-infra.svc.cluster.local"
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: "http://minio.face-infra.svc.cluster.local:9000"
  MINIO_BUCKET: "face-images"
  FACE_SERVICE_URL: "http://face-recognition-service.face-app.svc.cluster.local:5000"
  RABBITMQ_HOST: "rabbitmq.face-infra.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  ELASTICSEARCH_URIS: "http://elasticsearch.face-infra.svc.cluster.local:9200"
  VAULT_ADDR: "http://vault.face-infra.svc.cluster.local:8200"
  JWT_ACCESS_TOKEN_EXPIRATION: "3600000"
  JWT_REFRESH_TOKEN_EXPIRATION: "604800000"
  FRONTEND_URL: "http://face.local"
